### ISSUE TITLE
[Error] make -j5

### ISSUE THREAD

**Issue by RayX47** [idiap/zentas#2]
zentas/CMakeFiles/zentas.dir/build.make:422: recipe for target 'zentas/CMakeFiles/zentas.dir/src/textfilezentas.cpp.o' failed

make[2]: *** [zentas/CMakeFiles/zentas.dir/src/textfilezentas.cpp.o] Error 1
zentas/CMakeFiles/zentas.dir/build.make:158: recipe for target 'zentas/CMakeFiles/zentas.dir/src/dispatch.cpp.o' failed

make[2]: *** [zentas/CMakeFiles/zentas.dir/src/dispatch.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'zentas/CMakeFiles/zentas.dir/all' failed

make[1]: *** [zentas/CMakeFiles/zentas.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

would you please tell me how to fix it?

**Comment by newling** [comment]
Can you provide the log from the cmake configuration step?

**Comment by RayX47** [comment]
Errorlog.log

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/xys/Documents/zentas/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ad96a/fast"
/usr/bin/make -f CMakeFiles/cmTC_ad96a.dir/build.make CMakeFiles/cmTC_ad96a.dir/build
make[1]: Entering directory '/home/xys/Documents/zentas/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ad96a.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_ad96a.dir/CheckSymbolExists.c.o   -c /home/xys/Documents/zentas/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_ad96a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ad96a.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_ad96a.dir/CheckSymbolExists.c.o  -o cmTC_ad96a 
CMakeFiles/cmTC_ad96a.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ad96a.dir/build.make:97: recipe for target 'cmTC_ad96a' failed
make[1]: *** [cmTC_ad96a] Error 1
make[1]: Leaving directory '/home/xys/Documents/zentas/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ad96a/fast' failed
make: *** [cmTC_ad96a/fast] Error 2

File /home/xys/Documents/zentas/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/xys/Documents/zentas/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_99d9f/fast"
/usr/bin/make -f CMakeFiles/cmTC_99d9f.dir/build.make CMakeFiles/cmTC_99d9f.dir/build
make[1]: Entering directory '/home/xys/Documents/zentas/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_99d9f.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_99d9f.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_99d9f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_99d9f.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_99d9f.dir/CheckFunctionExists.c.o  -o cmTC_99d9f -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_99d9f.dir/build.make:97: recipe for target 'cmTC_99d9f' failed
make[1]: *** [cmTC_99d9f] Error 1
make[1]: Leaving directory '/home/xys/Documents/zentas/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_99d9f/fast' failed
make: *** [cmTC_99d9f/fast] Error 2

**Comment by newling** [comment]
I don't know what Errorlog.log is. What steps have you taken to build zentas? Have you followed the configuration steps described in the instructions? i.e. mkdir build; cd build; cmake ..;  What OS are you using?

**Comment by RayX47** [comment]
Yes,I did. but there are some errors when I did "make -j5"
Did I lose some library?
OS:ubuntu18.04

**Comment by newling** [comment]
Ok, thanks. 

> Can you provide the log from the cmake configuration step?

So there was no error when you ran `cmake ..` in the build dir? I'm a bit surprised, as your threading problem _should_ have been detected when you ran `cmake ..`, as CMakeLists.txt has `find_package (Threads REQUIRED)` in it. 

This line in your log 
```
/usr/bin/ld: cannot find -lpthreads
```

tells me the problem is with linking to lpthreads. Is the log above the full log from running `make -j5` in the build directory where you ran `cmake ..`?

I can't remember if I tested zentas on ubuntu, I was using debian when I developed it, but I'd be surprised if that's the issue.

**Comment by RayX47** [comment]
![image](https://user-images.githubusercontent.com/35096520/60059855-d3393480-9720-11e9-9eaf-16eecb49304e.png)

That's so weird.

**Comment by RayX47** [comment]
Excuse me, what is your cmake version and g++ version?
Now there is just an error.

> error: ‘mt19937_64’ is not a member of ‘std’ std::mt19937_64

Thanks for your generous reply.

**Comment by newling** [comment]
That's a missing header error. I have updated zentas with this diff  d820e45c95125cfe25147343df95e801abee4ba9 to fix zentas. Please pull the repo again. 

Getting closer :)

**Comment by RayX47** [comment]
OK, it's work. Thank you very much.

In addition,  this is another missing header error in head file.
>  zentas/zentas/include/zentas/lpmetric.hpp
`#include <functional>`

**Comment by newling** [comment]
Thank you. I have added this header too.

**Comment by RayX47** [comment]
Thanks a lot!
